# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: stagingpw

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: hb8OzfSdnEBw
    salt: "fTEKK9He"

# Variables to accompany `group_vars/staging/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  autoscenic.com:
    env:
        db_password: hb8OzfSdnEBw
        acf_pro_key: b3JkZXJfaWQ9MTA1OTEwfHR5cGU9cGVyc29uYWx8ZGF0ZT0yMDE3LTA1LTA4IDE5OjMzOjQ1
        # Generate your keys here: https://roots.io/salts.html
        auth_key: "}pwn6>O#QkjFLWX*wd$B6F$qCYYg|MBLkgM|!hx4/XYPcZ2U{<q;d<2*fUqATa^/"
        secure_auth_key: "T.d?`cKb`6x;JtzS=g+{nxitdP$A2(Mk2hvtrc*%$7Ch26$0vBeC7^4uRq5&<e`0"
        logged_in_key: "Z?:)EEz8H1@fSANRZ-l%B=;T/()wnn`nHO$;fLgBv!+}d>tEJN*#]kh[/}Ibb:|K"
        nonce_key: "uj$g5wQ5gu`$LLk=j6;F&q(CsN2]#)F>J|gAy4TuEL!J8P+Q8-q!sKU#M/zlZ28*"
        auth_salt: "H$qKMr_E=!@bp/4OOC<|:-BCGH96&Oyl;F{iojuVQ5R|?ia:o#t#6l]=w+li>de("
        secure_auth_salt: "U%Rz&7[fs2JI,)X2L^M%nA3<TFtAL|<aZ#CgisU=G1<c?={B}O^A)UFYe-U`P}xF"
        logged_in_salt: "EQmzIJ!7QE5Ql%{aao(fqfnjBiLLvjGO_tmMPVNJ}P%cK>a4wM*H]]3OX}jen@-U"
        nonce_salt: "N4uC`uKS.7*K=L@eer.a7xxQ7Cvl3]MGZZM#=z?[|:$GckTo_ZfVj$BD*6.SIwa+"
